### ISSUE TITLE
ReferenceError: require is not defined at preview.js:1:1

### ISSUE THREAD

**Issue by laneschmidt** [stevensacks/storybook-react-i18next#11]
Hey 🤝
So I am getting this error/loading spinner...
<img width="576" alt="Screen Shot 2022-03-30 at 4 45 21 PM" src="https://user-images.githubusercontent.com/38232529/160943239-135d5fa1-f5b1-442d-8762-6a895cb76733.png">

```
ReferenceError: require is not defined
    at preview.js:1:1
```
<img width="707" alt="Screen Shot 2022-03-30 at 5 02 39 PM" src="https://user-images.githubusercontent.com/38232529/160944831-c0ec2d4b-e8d2-45ed-b62b-bf6db99f845f.png">

Similar to this [issue](https://github.com/storybookjs/storybook/issues/17176), though the proposed solution there was to remove the addon 😅 

After following the docs to add this to my package, i ended up with the following pieces:

### `package.json` (only relevant pkgs)
```json
"dependencies": {
    "i18next": "^21.6.14",
    "react": "18.0.0",
    "react-dom": "18.0.0",
    "react-i18next": "^11.16.2",
    "react-router-dom": "6.2.2"
  },
  "devDependencies": {
    "@storybook/addon-actions": "6.5.0-alpha.51",
    "@storybook/addon-essentials": "6.5.0-alpha.51",
    "@storybook/addon-links": "6.5.0-alpha.51",
    "@storybook/addon-postcss": "2.0.0",
    "@storybook/client-api": "6.5.0-alpha.51",
    "@storybook/client-logger": "6.5.0-alpha.51",
    "@storybook/core-common": "6.5.0-alpha.51",
    "@storybook/react": "6.5.0-alpha.51",
    "storybook-builder-vite": "0.1.22",
    "storybook-react-i18next": "^1.0.18",
    "typescript": "4.6.3",
    "vite": "2.9.0"
```

### `preview.js`
```javascript
import { i18n } from './i18next.js';
import '../src/output.css';

export const parameters = {
  i18n,
  locale: 'en',
  locales: {
    en: 'English',
    fr: 'Français',
  },
  actions: { argTypesRegex: '^on[A-Z].*' },
  controls: {
    matchers: {
      color: /(background|color)$/i,
      date: /Date$/,
    },
  },
};
```

### `main.js`

```javascript
module.exports = {
  stories: ['../src/**/*.stories.mdx', '../src/**/*.stories.@(js|jsx|ts|tsx)'],
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    'storybook-react-i18next',
  ],
  framework: '@storybook/react',
  core: {
    builder: 'storybook-builder-vite',
  },
};

```

### `i18next.js`

```javascript
import { initReactI18next } from 'react-i18next';
import i18n from 'i18next';
import LanguageDetector from 'i18next-browser-languagedetector';

const ns = ['common'];
const supportedLngs = ['en', 'fr'];

i18n.use(LanguageDetector)
  .use(initReactI18next)
  .init({
    debug: true,
    lng: 'en',
    fallbackLng: 'en',
    interpolation: {
        escapeValue: false,
    },
    defaultNS: 'common',
    ns,
    supportedLngs,
  });

supportedLngs.forEach((lang) => {
  ns.forEach((n) => {
    i18n.addResourceBundle(
      lang,
      n,
      require(`../public/locales/${lang}/${n}.json`),
    );
  });
});

export { i18n };
```

**Comment by laneschmidt** [comment]
storybook is running fine on react 18.

**Comment by thomasverleye** [comment]
Hi,

Just going to mention [this](https://github.com/stevensacks/storybook-react-i18next/issues/2#issuecomment-1141290987) here.

👋

**Comment by stevensacks** [comment]
I have updated the plugin to no longer use suspense. Please check the updated README instructions.
